name: example pipeline

on:
  push:
    branches: [ develop ]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
        
      - name: Ver directorio
        run: ls -l
